substitutions:
  device_name: remora

external_components:
  - source: ../esphome/components
    components: [host_exec]

esphome:
  name: ${device_name}

host:
host_exec:

api:
logger:

button:
  - platform: host_exec
    name: "Shutdown"
    command: "systemctl poweroff"

  - platform: host_exec
    name: "Display DVI"
    command: "ddcutil setvcp 0x60 0x03"

  - platform: host_exec
    name: "Display HDMI"
    command: "ddcutil setvcp 0x60 0x11"

  - platform: host_exec
    name: "Display On"
    command: "ddcutil setvcp 0xD6 0x01"

  - platform: host_exec
    name: "Display Standby"
    command: "ddcutil setvcp 0xD6 0x04"

  - platform: host_exec
    name: "Display Off"
    command: "ddcutil setvcp 0xD6 0x05"
